export const mockInput = [
  {
    'identification.typeOfDeath': 'Não fetal',
    'identification.dateOfDeath': '2024-10-05',
    'identification.hourOfDeath': '14:30',
    'identification.deceasedName': 'João da Silva',
    'identification.mothersName': 'Maria da Silva',
    'identification.fathersName': 'José da Silva',
    'identification.naturalness': 'São Paulo',
    'identification.dateOfBirth': '1980-05-20',
    'identification.age': '44',
    'identification.sex': 'M',
    'identification.race': 'Branca',
    'identification.maritalStatus': 'Casado(a)',
    'identification.susCard': '123456789',
    'identification.education': 'Superior completo',
    'identification.class': 'Classe A',
    'identification.occupation': 'Engenheiro',
    'identification.cbo': '214101',
    'identification.deceasedAddress.zipCode': '01001-000',
    'identification.deceasedAddress.number': '123',
    'identification.deceasedAddress.complement': 'Apto 45',
    'identification.deceasedAddress.neighborhood': 'Centro',
    'identification.deceasedAddress.city': 'São Paulo',
    'identification.deceasedAddress.state': 'SP',
    'identification.deceasedAddress.street': 'Rua das Flores',
    'occurrence.address.zipCode': '01002-000',
    'occurrence.address.number': '456',
    'occurrence.address.neighborhood': 'Bela Vista',
    'occurrence.address.city': 'São Paulo',
    'occurrence.address.state': 'SP',
    'occurrence.address.street': 'Avenida Paulista',
    'occurrence.cnes': '1234567',
    'occurrence.establishmentName': 'Hospital São Paulo',
    'occurrence.hospitalAddress.zipCode': '01003-000',
    'occurrence.hospitalAddress.number': '789',
    'occurrence.hospitalAddress.neighborhood': 'Liberdade',
    'occurrence.hospitalAddress.city': 'São Paulo',
    'occurrence.hospitalAddress.state': 'SP',
    'occurrence.hospitalAddress.street': 'Rua Vergueiro',
    'occurrence.placeType': 'Hospital',
    'infant.mothersAge': '30',
    'infant.mothersEducation': 'Médio (antigo 2º grau)',
    'infant.mothersClass': 'Classe B',
    'infant.mothersOccupation': 'Professora',
    'infant.bornAlive': 'Sim',
    'infant.fetalLoss': 'Não',
    'infant.weeksPregnant': '38',
    'infant.pregnancyType': 'Única',
    'infant.birthType': 'Cesárea',
    'infant.birthWeight': '3200',
    'infant.deathRelativeToBirth': 'Imediatamente após',
    'infant.birthCertificateNumber': '987654321',
    'conditions.fertileAgeDeath': 'Sim',
    'conditions.receivedMedicalAssistance': 'Sim',
    'conditions.necropsy': 'Sim',
    'conditions.cause1': 'Infarto',
    'conditions.evolutionTime1': '02:00',
    'conditions.cid1': 'I21.9',
    'conditions.cause2': 'Insuficiência Respiratória',
    'conditions.evolutionTime2': '00:30',
    'conditions.cid2': 'J96.0',
    'doctor.name': 'Dr. Roberto Mendes',
    'doctor.crm': '123456-SP',
    'doctor.confirmedBy': 'Assistente',
    'doctor.city': 'São Paulo',
    'doctor.contact': '11987654321',
    'doctor.confirmationDate': '2024-10-06',
    'external.nonNaturalType': 'Acidente',
    'external.workplaceAccident': 'Não',
    'external.informationSource': 'Hospital',
    'external.placeType': 'Via pública',
    'external.occurrenceNumber': '789123',
    'external.occurrenceDescription': 'Acidente de carro',
    'external.occurrenceAddress.zipCode': '01004-000',
    'external.occurrenceAddress.number': '101',
    'external.occurrenceAddress.neighborhood': 'Sé',
    'external.occurrenceAddress.city': 'São Paulo',
    'external.occurrenceAddress.state': 'SP',
    'external.occurrenceAddress.street': 'Rua da Consolação',
  },
];
